### ISSUE TITLE
In presence of network issues you can get null ref

### ISSUE THREAD

**Issue by mtuchkov** [mongodb-js/mongodb-core#299]
/Users/mtuchkov/GitHub/saas/node_modules/mongodb-core/lib/topologies/replset_state.js:149
  var serverName = server.name.toLowerCase();
                          ^

TypeError: Cannot read property 'name' of null
    at ReplSetState.remove (/Users/mtuchkov/GitHub/saas/node_modules/mongodb-core/lib/topologies/replset_state.js:149:27)
    at Object.handler [as cb] (/Users/mtuchkov/GitHub/saas/node_modules/mongodb-core/lib/topologies/replset.js:1221:28)
    at Connection.<anonymous> (/Users/mtuchkov/GitHub/saas/node_modules/mongodb-core/lib/connection/pool.js:299:33)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at TLSSocket.<anonymous> (/Users/mtuchkov/GitHub/saas/node_modules/mongodb-core/lib/connection/connection.js:256:10)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)

**Comment by mbroadst** [comment]
Hi @mtuchkov, can you please open a JIRA ticket for this and specify what version of the driver you are using, and optionally reproduction steps? Thank you.
