### ISSUE TITLE
Internal error in case of a connection timeout

### ISSUE THREAD

**Issue by Ulrikop** [mongodb-js/mongodb-core#435]
In case of a connection timeout because of an slow connection, an internal error is thrown:

```
TypeError: Cannot read property 'message' of undefined
    at new MongoError (node_modules/mongodb-core/lib/error.js:22:23)
    at new MongoNetworkError (node_modules/mongodb-core/lib/error.js:60:5)
    at Socket.err (node_modules/mongodb-core/lib/connection/connect.js:287:16)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:459:23)
    at Socket._onTimeout (net.js:443:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

But the `.on('error')` is not called.

**Used version**

mongodb-core: 3.2.4

I used the mongodb together with mongoose version 5.5.8

With version 3.2.2 of mongodb-core it was working like expected (I haven't tested it with 3.2.3)

**Comment by mbroadst** [comment]
Hi @Ulrikop, this was actually fixed in the most recent commit https://github.com/mongodb-js/mongodb-core/commit/83e224be0727438697a2bae3b01af381ab6efe90, would you be willing to try  with that version? You should be able to override the installed `mongodb-core` version like so:
```
"dependencies": {
   "mongodb": "^3.2.4",
   "mongodb-core": "mongodb-js/mongodb-core#master"
}
```

**Comment by Ulrikop** [comment]
hi @mbroadst thx for the fast answer. I tried the master and it works again!

**Comment by mbroadst** [comment]
@Ulrikop great to hear it!
