### ISSUE TITLE
Error: MongoWriteConcernError - No write concern mode named

### ISSUE THREAD

**Issue by soumojit** [mongodb-js/mongodb-core#443]
I am using a mongo_db cluster hosted on atlas and strapi for my project. 

The connection string from atlas contains "w=majority". When I add this to my database config as host, its giving me the following error. Everything works fine if I remove it. 

```
error MongoWriteConcernError: No write concern mode named 'majority/' found in replica set configuration
    at Connection.<anonymous> (../../node_modules/mongodb-core/lib/connection/pool.js:438:23)
    at Connection.emit (events.js:196:13)
    at processMessage (../../node_modules/mongodb-core/lib/connection/connection.js:364:10)
    at TLSSocket.<anonymous> (../../node_modules/mongodb-core/lib/connection/connection.js:533:15)
    at TLSSocket.emit (events.js:196:13)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)
    at TLSSocket.Readable.push (_stream_readable.js:226:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:166:17) {
  code: 79,
  codeName: 'UnknownReplWriteConcern',
  errmsg: "No write concern mode named 'majority/' found in replica set configuration",
  name: 'MongoWriteConcernError',
  result: {
    n: 1,
    nModified: 0,
    opTime: { ts: [Timestamp], t: 1 },
    electionId: 7fffffff0000000000000001,
    ok: 1,
    writeConcernError: {
      code: 79,
      codeName: 'UnknownReplWriteConcern',
      errmsg: 'No write concern mode named ' +
        "'majority/' found in replica set " +
        'configuration'
    },
    operationTime: Timestamp { _bsontype: 'Timestamp', low_: 17, high_: 1561819567 },
    '$clusterTime': { clusterTime: [Timestamp], signature: [Object] }
  },
  [Symbol(mongoErrorContextSymbol)]: {}
}
(node:30378) UnhandledPromiseRejectionWarning: MongoWriteConcernError: No write concern mode named 'majority/' found in replica set configuration
    at Connection.<anonymous> (../../node_modules/mongodb-core/lib/connection/pool.js:438:23)
    at Connection.emit (events.js:196:13)
    at processMessage (../../node_modules/mongodb-core/lib/connection/connection.js:364:10)
    at TLSSocket.<anonymous> (../../node_modules/mongodb-core/lib/connection/connection.js:533:15)
    at TLSSocket.emit (events.js:196:13)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)
    at TLSSocket.Readable.push (_stream_readable.js:226:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:166:17)
(node:30378) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30378) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mbroadst** [comment]
Hi @soumojit, can you please open a JIRA ticket for this? I am going to be disabling issues on this project later today, as the project is deprecated (it's been merged into the main driver as of the upcoming v3.3.0 release). In your JIRA ticket please make sure to include the connection string you are using, it seems likely that there is some sort of parsing error here.
