### ISSUE TITLE
UncaughtException from the driver when connection is refused

### ISSUE THREAD

**Issue by mckn** [mongodb-js/mongodb-core#459]
Running the driver against mongodb atlas and for some reason it rejected the connection which caused the following error:

`{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"*.*.*.*","port":27017}`

Which in turn caused the following error:

```js
TypeError: Cannot read property 'message' of undefined
    at new MongoError (/usr/src/app/node_modules/mongodb-core/lib/error.js:22:23)
    at new MongoNetworkError (/usr/src/app/node_modules/mongodb-core/lib/error.js:60:5)
    at TLSSocket.err (/usr/src/app/node_modules/mongodb-core/lib/connection/connect.js:287:16)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
    at TLSSocket.Socket._onTimeout (net.js:443:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**Comment by mbroadst** [comment]
Hi @mckn, this project is deprecated. Please refer to our instructions on [submitting a bug report](https://github.com/mongodb/node-mongodb-native#bugs--feature-requests) for help. Thanks!

**Comment by mckn** [comment]
thanks, then I will skip it. A bit too much friction to create jira account etc.
